site_name: Doc Snippet
site_author: 'zhoujiagen@gmail.com'
copyright: MIT
repo_name: doc-snippet
repo_url: https://github.com/zhoujiagen/doc-snippet

nav:
    - Home: index.md
    - Readings: readings.md
    - '参考文献': references.md
    - Java:
      - 'JVM Tool Interface': java/jvmti_demo.md
      - 'HotSpot Concepts': java/openjdk_hotspot_concepts.md
      - 'HotSpot RTFSC': java/openjdk_hotspot_rtfsc.md
      - 'GC': java/gc.md
      - 'Spring': java/spring.md
      - 'Guice': java/guice.md
      - 'Java SE': java/javase.md
      - 'Java EE': java/javaee.md
    - Editor:
      - Eclipse: editor/eclipse.md
      - 'IntelliJ IDEA': editor/idea.md
      - Atom: editor/atom.md
      - Emacs: editor/emacs.md
      - GNU: editor/gnu.md
      - Jupyter: editor/jupyter.md
    - Tools:
      - Git: tools/git.md
      - Maven: tools/maven.md
      - Gradle: tools/gradle.md
    - Prolog:
      - 'Prolog逻辑编程': prolog/prolog.md
    - Datalog:
      - 'Syntax': datalog/syntax.md
    - Haskell:
      - 'Tutorial': haskell/tutorial.md
      - 'Tool': haskell/tool.md
      - 'Library': haskell/lib.md

#theme: readthedocs
theme:
  name: material
extra:
  search:
    language: 'en'
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
      guess_lang: False
  - toc:
      permalink: true
  - pymdownx.arithmatex # LaTeX math equations
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - markdown_inline_graphviz

extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - https://cdn.jsdelivr.net/npm/mermaid/dist/mermaid.min.js
